### ISSUE TITLE
Prepare files for MCScanX Wiki mistake

### ISSUE THREAD

**Issue by SJ-Smit** [conJUSTover/pSONIC#1]
The instructions in the wiki under "2. Prepare files for MCScanX" is incorrect. The gff order for mcscanx should be 
Sp## GeneID Start_POS End_POS.

**Comment by conJUSTover** [comment]
Ah, thanks for catching this! I've updated the README to correct this error.

**Comment by SJ-Smit** [comment]
Thanks. One more tiny thing. The Orthogroups output on my side is by default saved as .tsv eventhough it is actualy a csv file. I manually changed the extension to csv. Kept getting an error when running translate_gff until I changed the extension.

**Comment by conJUSTover** [comment]
That is a change that OrthoFinder implemented after I wrote that block of code. The format between the .csv and the .tsv didn't change from what I can tell, so your run shouldn't be affected.

I've created a new issue to fix this. In the meantime, when using `--translate_gff` I believe you can use the `-og` flag and feed it a file with the .tsv extension, and it should still work fine. It's a more reproducible alternative than manually changing your file extension.
