### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by ssamberkar** [conJUSTover/pSONIC#9]
Hey Justin,

Beyond the output of MCScanX and possible multiple sequence alignments of the orthogroups, do you have any suggestions for visualising the main output i.e. the refined syntenic collinear blocks from pSONIC? I'm interested in a network based visualisation from the edgelist file, if you can help.

**Comment by conJUSTover** [comment]
I don't have any current scripts that can do visualizations in python, sorry. If you come up with anything, feel free to share if you'd like!
